timing.hpp: Casting to atomic uint64_t before Running/last_ assignment
This patch adds a cast for an assignment to an atomic integer value
in timing.hpp

Previous to the patch, compiling Rubinius v5.0 with clang 11 on
FreeBSD 11.1:

~~~~
4: CXX machine/accessor_primitives.cpp
In file included from machine/accessor_primitives.cpp:9:
In file included from /usr/home/u1000/wk/dist_wk/ports_devo/lang/rubinius/work/rubinius-5.0/machine/includes.hpp:15:
In file included from ./machine/class/block_environment.hpp:12:
In file included from /usr/home/u1000/wk/dist_wk/ports_devo/lang/rubinius/work/rubinius-5.0/machine/class/variable_scope.hpp:9:
In file included from /usr/home/u1000/wk/dist_wk/ports_devo/lang/rubinius/work/rubinius-5.0/machine/class/fiber.hpp:13:
/usr/home/u1000/wk/dist_wk/ports_devo/lang/rubinius/work/rubinius-5.0/machine/diagnostics/timing.hpp:116:25: error: incompatible integer to pointer conversion assigning to 'std::atomic<uint>
      if(last_) last_ = run;
                        ^~~
In file included from machine/bytecode_verifier.cpp:17:
/usr/home/u1000/wk/dist_wk/ports_devo/lang/rubinius/work/rubinius-5.0/machine/diagnostics/timing.hpp:116:25: error: incompatible integer to pointer conversion assigning to 'std::atomic<uint>
      if(last_) last_ = run;
                        ^~~
~~~~

(cherry picked from commit 34b987a3bf35c6390e36222b75cb233617329bc2)